NOTANGLE=notangle
NOWEAVE=noweave
#CPIF=>
CPIF=| cpif
L2H=l2h

.SUFFIXES: .nw .ltx .pdf .html
.nw.html:
	$(NOWEAVE) -filter $(L2H) -index -html $< $(CPIF) $@
.nw.ltx:
	$(NOWEAVE) -index $< $(CPIF) $@
.ltx.pdf:
	latexmk -pdf $<
